In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

df = pd.read_csv(r"C:\Users\khush\Downloads\archive\WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [2]:
df.head(5)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [4]:
df.TotalCharges = pd.to_numeric(df.TotalCharges,errors='coerce')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [6]:
df.dropna(how='any' , inplace= True)

In [8]:
len(df)

7032

In [10]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.421502
Yes    26.578498
Name: count, dtype: float64

In [11]:
X = df.drop(['customerID','Churn'] , axis=1) 
y=df.Churn.values

In [12]:
X

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50

In [13]:
y

array(['No', 'No', 'Yes', ..., 'No', 'Yes', 'No'],
      shape=(7032,), dtype=object)

In [14]:
# convert categorcial attributes to numerical attribute -- > feature encoding
X = pd.get_dummies(X,columns = ['gender', 'Partner', 'Dependents','PhoneService',
        'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod'],drop_first = True)

In [15]:
bool_cols = X.select_dtypes(include='bool').columns
X[bool_cols] = X[bool_cols].astype(int)

In [16]:
X.head(1)

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,1,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0

In [17]:
# splitting the data into traing nd testing 
from sklearn.model_selection import train_test_split
X_train,X_test ,y_train,y_test  = train_test_split(X,y,test_size=0.25)

In [18]:
# feature scaling :
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [20]:
X_train_sc

array([[-0.4377158 , -0.91190843,  1.23539132, ...,  1.89369664,
        -0.71647952, -0.54477422],
       [-0.4377158 , -0.95270932, -1.01123873, ...,  1.89369664,
        -0.71647952, -0.54477422],
       [-0.4377158 ,  0.8425299 ,  0.96206244, ..., -0.52806769,
         1.39571331, -0.54477422],
       ...,
       [-0.4377158 ,  1.08733525, -1.49456419, ..., -0.52806769,
        -0.71647952, -0.54477422],
       [-0.4377158 ,  0.39372009, -1.5162305 , ..., -0.52806769,
        -0.71647952,  1.83562283],
       [ 2.28458741,  1.00573346, -0.33458309, ..., -0.52806769,
         1.39571331, -0.54477422]], shape=(5274, 30))

In [21]:
X_test_sc

array([[-0.4377158 , -0.17749239,  0.87373055, ..., -0.52806769,
        -0.71647952, -0.54477422],
       [-0.4377158 ,  1.57694594, -1.37123287, ...,  1.89369664,
        -0.71647952, -0.54477422],
       [-0.4377158 , -1.27911645,  0.53373609, ..., -0.52806769,
         1.39571331, -0.54477422],
       ...,
       [-0.4377158 , -0.46309863,  1.16039254, ...,  1.89369664,
        -0.71647952, -0.54477422],
       [-0.4377158 , -1.19751467,  1.00206179, ..., -0.52806769,
         1.39571331, -0.54477422],
       [-0.4377158 , -0.29989506, -1.32456696, ..., -0.52806769,
        -0.71647952, -0.54477422]], shape=(1758, 30))

In [22]:
## KNN  CLASSIFIER  
from sklearn.neighbors import KNeighborsClassifier

# initiating my classifier 
model = KNeighborsClassifier()

# passing the value to classifier
model.fit(X_train_sc,y_train)

KNeighborsClassifier()

In [23]:
 y_pred = model.predict(X_test_sc)

In [24]:
# classification metririx 
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred)*100)

76.67804323094425

In [25]:
## decison tree classifier  
from sklearn.tree import DecisionTreeClassifier 
#initiating the classifier 
model_dt = DecisionTreeClassifier()  
#passing the data to classifier 
model_dt.fit(X_train_sc,y_train)

DecisionTreeClassifier()

In [26]:
y_pred_dt = model_dt.predict(X_test_sc)

In [27]:
# classification metririx 
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred_dt)*100)

73.83390216154721

In [31]:
# random forest classifier 
from sklearn.ensemble import RandomForestClassifier

# initiating the classifier
model = RandomForestClassifier(n_estimators=200)

# passing the data to classifier
model.fit(X_train_sc,y_train)

RandomForestClassifier(n_estimators=200)

In [32]:
y_pred_rn = model.predict(X_test_sc)

In [33]:
# classification metririx 
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred_rn)*100)

79.06712172923777

In [36]:
from sklearn.metrics import classification_report 
knn_report  = classification_report(y_test,y_pred)
dt_report = classification_report(y_test,y_pred_dt)
rn_report = classification_report(y_test,y_pred_rn)

In [37]:
print('KNN CLASSIFIER' , knn_report)

KNN CLASSIFIER               precision    recall  f1-score   support

          No       0.84      0.85      0.84      1304
         Yes       0.55      0.52      0.53       454

    accuracy                           0.77      1758
   macro avg       0.69      0.68      0.69      1758
weighted avg       0.76      0.77      0.76      1758

In [40]:
print('DECISION FOREST CLASSIFIER',dt_report)

DECISION FOREST CLASSIFIER               precision    recall  f1-score   support

          No       0.82      0.82      0.82      1304
         Yes       0.49      0.49      0.49       454

    accuracy                           0.74      1758
   macro avg       0.66      0.66      0.66      1758
weighted avg       0.74      0.74      0.74      1758

In [41]:
print('RANDOM FOREST CLASSIFIER ', rn_report)

RANDOM FOREST CLASSIFIER                precision    recall  f1-score   support

          No       0.83      0.90      0.86      1304
         Yes       0.62      0.48      0.54       454

    accuracy                           0.79      1758
   macro avg       0.73      0.69      0.70      1758
weighted avg       0.78      0.79      0.78      1758

In [42]:
 # NAIVE BAYES CLASSIFIER
from sklearn.naive_bayes import BernoulliNB 

# initiating my classifier
model_nb = BernoulliNB()

# passing the data to classifier
model_nb.fit(X_train_sc,y_train) 

# prediction
y_pred_nb = model_nb.predict(X_test_sc)

# accuracy 
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred_nb)*100)

74.06143344709898

In [49]:
nb_report = classification_report(y_test,y_pred_nb)
print(nb_report)

              precision    recall  f1-score   support

          No       0.91      0.72      0.80      1304
         Yes       0.50      0.81      0.62       454

    accuracy                           0.74      1758
   macro avg       0.71      0.76      0.71      1758
weighted avg       0.81      0.74      0.76      1758

In [44]:
# SVM CLASSIFIER 
from sklearn.svm import SVC 

# initiating my classifier
model_svc = SVC()

# passing the data to classifier
model_svc.fit(X_train_sc,y_train) 

# prediction
y_pred_svc = model_svc.predict(X_test_sc)

# accuracy 
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred_svc)*100)

79.57906712172924

In [48]:
svc_report = classification_report(y_test,y_pred_svc)
print(svc_report)

              precision    recall  f1-score   support

          No       0.83      0.90      0.87      1304
         Yes       0.64      0.48      0.55       454

    accuracy                           0.80      1758
   macro avg       0.74      0.69      0.71      1758
weighted avg       0.78      0.80      0.79      1758

In [45]:
# LOGISTIC REGRESSION 
from sklearn.linear_model import LogisticRegression

# initiating my classifier
model_lr = LogisticRegression()

# passing the data to classifier
model_lr.fit(X_train_sc,y_train) 

# prediction
y_pred_lr = model_lr.predict(X_test_sc)

# accuracy 
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred_lr)*100)

79.97724687144482

In [47]:
lr_report = classification_report(y_test,y_pred_lr)
print(lr_report)

              precision    recall  f1-score   support

          No       0.85      0.89      0.87      1304
         Yes       0.63      0.53      0.58       454

    accuracy                           0.80      1758
   macro avg       0.74      0.71      0.72      1758
weighted avg       0.79      0.80      0.79      1758